query {
  organization(login: "OneForAll20240313") {
    projectV2(number: 6) {
      title
      items(first: 100) {
        totalCount
        nodes {
          content {
            ... on Issue {
              number
              title
              assignees(first: 5) {
                totalCount
                nodes { login }
              }
              milestone { title }
            }
          }
          status: fieldValueByName(name: "Status") {
            ... on ProjectV2ItemFieldSingleSelectValue {
              name
            }
          }
        }
      }
    }
  }
}